export const EPOCH_START_MENTORING = 1753340400;
export const EPOCH_ENDS_MENTORING = 1753448400;

export const ONE_SLOT_INTERVAL_MINUTES = 15; // one mentorship slot is defined as 15 minutes

export const TOTAL_DURATION_SECONDS = EPOCH_ENDS_MENTORING - EPOCH_START_MENTORING;
export const TOTAL_DURATION_MINUTES = TOTAL_DURATION_SECONDS / 60;
export const PIXELS_PER_MINUTE = 2;
export const TOTAL_HEIGHT = TOTAL_DURATION_MINUTES * PIXELS_PER_MINUTE;
export const HOUR_HEIGHT = 60 * PIXELS_PER_MINUTE;